name: test2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
      - name: Node js version
        run: node -v
      - name: Install Netlify CLI
        run: npm install netlify-cli -g
      - name: Netlify Login
        run: netlify login
        env:
          NETLIFY_AUTH_TOKEN:  ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Initlize Netlify
        run: |
          netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir=dit
          echo 'y'
          echo 'dit'
        
      
