
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
      - uses: actions/setup-node@v1.4.3
      - name: Node js version
        run: node -v
